using System.Collections.Generic;

namespace Application.Helpers
{
    public static class CountryCodeHelper
    {
        private static readonly Dictionary<string, string> _countryCodes = new Dictionary<string, string>
        {
            { "Afghanistan", "+93" },
            { "Albania", "+355" },
            { "Algeria", "+213" },
            { "Andorra", "+376" },
            { "Angola", "+244" },
            { "Argentina", "+54" },
            { "Armenia", "+374" },
            { "Australia", "+61" },
            { "Austria", "+43" },
            { "Azerbaijan", "+994" },
            { "Bahrain", "+973" },
            { "Bangladesh", "+880" },
            { "Belarus", "+375" },
            { "Belgium", "+32" },
            { "Bhutan", "+975" },
            { "Bolivia", "+591" },
            { "Bosnia and Herzegovina", "+387" },
            { "Brazil", "+55" },
            { "Brunei", "+673" },
            { "Bulgaria", "+359" },
            { "Cambodia", "+855" },
            { "Cameroon", "+237" },
            { "Canada", "+1" },
            { "Chile", "+56" },
            { "China", "+86" },
            { "Colombia", "+57" },
            { "Costa Rica", "+506" },
            { "Croatia", "+385" },
            { "Cuba", "+53" },
            { "Cyprus", "+357" },
            { "Czech Republic", "+420" },
            { "Denmark", "+45" },
            { "Dominican Republic", "+1-809" },
            { "Ecuador", "+593" },
            { "Egypt", "+20" },
            { "El Salvador", "+503" },
            { "Estonia", "+372" },
            { "Ethiopia", "+251" },
            { "Fiji", "+679" },
            { "Finland", "+358" },
            { "France", "+33" },
            { "Georgia", "+995" },
            { "Germany", "+49" },
            { "Ghana", "+233" },
            { "Greece", "+30" },
            { "Guatemala", "+502" },
            { "Honduras", "+504" },
            { "Hong Kong", "+852" },
            { "Hungary", "+36" },
            { "Iceland", "+354" },
            { "India", "+91" },
            { "Indonesia", "+62" },
            { "Iran", "+98" },
            { "Iraq", "+964" },
            { "Ireland", "+353" },
            { "Israel", "+972" },
            { "Italy", "+39" },
            { "Jamaica", "+1-876" },
            { "Japan", "+81" },
            { "Jordan", "+962" },
            { "Kazakhstan", "+7" },
            { "Kenya", "+254" },
            { "Kuwait", "+965" },
            { "Kyrgyzstan", "+996" },
            { "Laos", "+856" },
            { "Latvia", "+371" },
            { "Lebanon", "+961" },
            { "Libya", "+218" },
            { "Liechtenstein", "+423" },
            { "Lithuania", "+370" },
            { "Luxembourg", "+352" },
            { "Macau", "+853" },
            { "Macedonia", "+389" },
            { "Madagascar", "+261" },
            { "Malawi", "+265" },
            { "Malaysia", "+60" },
            { "Maldives", "+960" },
            { "Mali", "+223" },
            { "Malta", "+356" },
            { "Mauritius", "+230" },
            { "Mexico", "+52" },
            { "Moldova", "+373" },
            { "Monaco", "+377" },
            { "Mongolia", "+976" },
            { "Montenegro", "+382" },
            { "Morocco", "+212" },
            { "Mozambique", "+258" },
            { "Myanmar", "+95" },
            { "Namibia", "+264" },
            { "Nepal", "+977" },
            { "Netherlands", "+31" },
            { "New Zealand", "+64" },
            { "Nicaragua", "+505" },
            { "Nigeria", "+234" },
            { "North Korea", "+850" },
            { "Norway", "+47" },
            { "Oman", "+968" },
            { "Pakistan", "+92" },
            { "Panama", "+507" },
            { "Paraguay", "+595" },
            { "Peru", "+51" },
            { "Philippines", "+63" },
            { "Poland", "+48" },
            { "Portugal", "+351" },
            { "Puerto Rico", "+1-787" },
            { "Qatar", "+974" },
            { "Romania", "+40" },
            { "Russia", "+7" },
            { "Saudi Arabia", "+966" },
            { "Senegal", "+221" },
            { "Serbia", "+381" },
            { "Singapore", "+65" },
            { "Slovakia", "+421" },
            { "Slovenia", "+386" },
            { "South Africa", "+27" },
            { "South Korea", "+82" },
            { "Spain", "+34" },
            { "Sri Lanka", "+94" },
            { "Sudan", "+249" },
            { "Sweden", "+46" },
            { "Switzerland", "+41" },
            { "Syria", "+963" },
            { "Taiwan", "+886" },
            { "Tajikistan", "+992" },
            { "Tanzania", "+255" },
            { "Thailand", "+66" },
            { "Tunisia", "+216" },
            { "Turkey", "+90" },
            { "Turkmenistan", "+993" },
            { "Uganda", "+256" },
            { "Ukraine", "+380" },
            { "United Arab Emirates (UAE)", "+971" },
            { "United Kingdom", "+44" },
            { "United States", "+1" },
            { "Uruguay", "+598" },
            { "Uzbekistan", "+998" },
            { "Venezuela", "+58" },
            { "Vietnam", "+84" },
            { "Yemen", "+967" },
            { "Zambia", "+260" },
            { "Zimbabwe", "+263" }
        };

        private static readonly Dictionary<string, string> _isoCodes = new Dictionary<string, string>(System.StringComparer.OrdinalIgnoreCase)
        {
            { "AF", "+93" },
            { "AL", "+355" },
            { "DZ", "+213" },
            { "AD", "+376" },
            { "AO", "+244" },
            { "AR", "+54" },
            { "AM", "+374" },
            { "AU", "+61" },
            { "AT", "+43" },
            { "AZ", "+994" },
            { "BH", "+973" },
            { "BD", "+880" },
            { "BY", "+375" },
            { "BE", "+32" },
            { "BT", "+975" },
            { "BO", "+591" },
            { "BA", "+387" },
            { "BR", "+55" },
            { "BN", "+673" },
            { "BG", "+359" },
            { "KH", "+855" },
            { "CM", "+237" },
            { "CA", "+1" },
            { "CL", "+56" },
            { "CN", "+86" },
            { "CO", "+57" },
            { "CR", "+506" },
            { "HR", "+385" },
            { "CU", "+53" },
            { "CY", "+357" },
            { "CZ", "+420" },
            { "DK", "+45" },
            { "DO", "+1" },
            { "EC", "+593" },
            { "EG", "+20" },
            { "SV", "+503" },
            { "EE", "+372" },
            { "ET", "+251" },
            { "FJ", "+679" },
            { "FI", "+358" },
            { "FR", "+33" },
            { "GE", "+995" },
            { "DE", "+49" },
            { "GH", "+233" },
            { "GR", "+30" },
            { "GT", "+502" },
            { "HN", "+504" },
            { "HK", "+852" },
            { "HU", "+36" },
            { "IS", "+354" },
            { "IN", "+91" },
            { "ID", "+62" },
            { "IR", "+98" },
            { "IQ", "+964" },
            { "IE", "+353" },
            { "IL", "+972" },
            { "IT", "+39" },
            { "JM", "+1" },
            { "JP", "+81" },
            { "JO", "+962" },
            { "KZ", "+7" },
            { "KE", "+254" },
            { "KW", "+965" },
            { "KG", "+996" },
            { "LA", "+856" },
            { "LV", "+371" },
            { "LB", "+961" },
            { "LY", "+218" },
            { "LI", "+423" },
            { "LT", "+370" },
            { "LU", "+352" },
            { "MO", "+853" },
            { "MK", "+389" },
            { "MG", "+261" },
            { "MW", "+265" },
            { "MY", "+60" },
            { "MV", "+960" },
            { "ML", "+223" },
            { "MT", "+356" },
            { "MU", "+230" },
            { "MX", "+52" },
            { "MD", "+373" },
            { "MC", "+377" },
            { "MN", "+976" },
            { "ME", "+382" },
            { "MA", "+212" },
            { "MZ", "+258" },
            { "MM", "+95" },
            { "NA", "+264" },
            { "NP", "+977" },
            { "NL", "+31" },
            { "NZ", "+64" },
            { "NI", "+505" },
            { "NG", "+234" },
            { "KP", "+850" },
            { "NO", "+47" },
            { "OM", "+968" },
            { "PK", "+92" },
            { "PA", "+507" },
            { "PY", "+595" },
            { "PE", "+51" },
            { "PH", "+63" },
            { "PL", "+48" },
            { "PT", "+351" },
            { "PR", "+1" },
            { "QA", "+974" },
            { "RO", "+40" },
            { "RU", "+7" },
            { "SA", "+966" },
            { "SN", "+221" },
            { "RS", "+381" },
            { "SG", "+65" },
            { "SK", "+421" },
            { "SI", "+386" },
            { "ZA", "+27" },
            { "KR", "+82" },
            { "ES", "+34" },
            { "LK", "+94" },
            { "SD", "+249" },
            { "SE", "+46" },
            { "CH", "+41" },
            { "SY", "+963" },
            { "TW", "+886" },
            { "TJ", "+992" },
            { "TZ", "+255" },
            { "TH", "+66" },
            { "TN", "+216" },
            { "TR", "+90" },
            { "TM", "+993" },
            { "UG", "+256" },
            { "UA", "+380" },
            { "AE", "+971" },
            { "GB", "+44" },
            { "US", "+1" },
            { "UY", "+598" },
            { "UZ", "+998" },
            { "VE", "+58" },
            { "VN", "+84" },
            { "YE", "+967" },
            { "ZM", "+260" },
            { "ZW", "+263" }
        };

        public static string GetCountryCode(string? countryNameOrCode)
        {
            if (string.IsNullOrEmpty(countryNameOrCode)) return "";

            var clean = countryNameOrCode.Trim();

            if (clean.StartsWith("+"))
            {
                return clean;
            }

            if (clean.Length == 2 && _isoCodes.TryGetValue(clean, out var dialCode))
            {
                return dialCode;
            }

            if (_countryCodes.TryGetValue(clean, out var resolvedDialCode))
            {
                return resolvedDialCode;
            }

            if (clean.All(char.IsDigit))
            {
                return "+" + clean;
            }

            return clean;
        }
    }
}
