// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240806061036_AddNoOfChildrenToRegistration")]
    partial class AddNoOfChildrenToRegistration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Application.Models.Transactions.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("amount");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("hash");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("key");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("PaymentGateway")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("payment_gateway");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.Property<string>("ProductInfo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("product_info");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("TxnId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("txn_id");

                    b.Property<string>("Udf1")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("udf1");

                    b.Property<long>("userId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_transaction");

                    b.HasIndex("userId")
                        .HasDatabaseName("ix_transaction_user_id");

                    b.ToTable("transaction", (string)null);
                });

            modelBuilder.Entity("Domain.About", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("BannerBody")
                        .HasColumnType("longtext")
                        .HasColumnName("banner_body");

                    b.Property<string>("BannerImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("banner_image_path");

                    b.Property<string>("BannerTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("banner_title");

                    b.Property<string>("Body")
                        .HasColumnType("longtext")
                        .HasColumnName("body");

                    b.Property<string>("ButtonTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("button_title");

                    b.Property<string>("ButtonUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("button_url");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<string>("FooterBody")
                        .HasColumnType("longtext")
                        .HasColumnName("footer_body");

                    b.Property<string>("Home1ImageAlt")
                        .HasColumnType("longtext")
                        .HasColumnName("home1image_alt");

                    b.Property<string>("Home1ImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("home1image_path");

                    b.Property<string>("Home2ImageAlt")
                        .HasColumnType("longtext")
                        .HasColumnName("home2image_alt");

                    b.Property<string>("Home2ImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("home2image_path");

                    b.Property<string>("Home3ImageAlt")
                        .HasColumnType("longtext")
                        .HasColumnName("home3image_alt");

                    b.Property<string>("Home3ImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("home3image_path");

                    b.Property<string>("HomeBody")
                        .HasColumnType("longtext")
                        .HasColumnName("home_body");

                    b.Property<string>("HomeButtonTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("home_button_title");

                    b.Property<string>("HomeButtonUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("home_button_url");

                    b.Property<string>("HomeTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("home_title");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_about");

                    b.ToTable("about", (string)null);
                });

            modelBuilder.Entity("Domain.BodyFeatures", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_body_features");

                    b.ToTable("body_features", (string)null);
                });

            modelBuilder.Entity("Domain.Community", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<long?>("Type")
                        .HasColumnType("bigint")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_community");

                    b.ToTable("community", (string)null);
                });

            modelBuilder.Entity("Domain.Contact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<string>("BannerBody")
                        .HasColumnType("longtext")
                        .HasColumnName("banner_body");

                    b.Property<string>("BannerImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("banner_image_path");

                    b.Property<string>("BannerTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("banner_title");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("FormTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("form_title");

                    b.Property<string>("GoogleMapUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("google_map_url");

                    b.Property<string>("ImageAlt")
                        .HasColumnType("longtext")
                        .HasColumnName("image_alt");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_contact");

                    b.ToTable("contact", (string)null);
                });

            modelBuilder.Entity("Domain.ContactEnquiry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Message")
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Purpose")
                        .HasColumnType("longtext")
                        .HasColumnName("purpose");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("pk_contact_enquiry");

                    b.ToTable("contact_enquiry", (string)null);
                });

            modelBuilder.Entity("Domain.FinancialStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_financial_status");

                    b.ToTable("financial_status", (string)null);
                });

            modelBuilder.Entity("Domain.Framework.Email", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<string>("EmailId")
                        .HasColumnType("longtext")
                        .HasColumnName("email_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<int>("Port")
                        .HasColumnType("int")
                        .HasColumnName("port");

                    b.Property<string>("Purpose")
                        .HasColumnType("longtext")
                        .HasColumnName("purpose");

                    b.Property<string>("Recipients")
                        .HasColumnType("longtext")
                        .HasColumnName("recipients");

                    b.Property<string>("SmtpServer")
                        .HasColumnType("longtext")
                        .HasColumnName("smtp_server");

                    b.HasKey("Id")
                        .HasName("pk_email");

                    b.ToTable("email", (string)null);
                });

            modelBuilder.Entity("Domain.HomeBanner", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasColumnType("longtext")
                        .HasColumnName("body");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<string>("ImageAlt")
                        .HasColumnType("longtext")
                        .HasColumnName("image_alt");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_home_banner");

                    b.ToTable("home_banner", (string)null);
                });

            modelBuilder.Entity("Domain.HomeContent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Body1")
                        .HasColumnType("longtext")
                        .HasColumnName("body1");

                    b.Property<string>("Body2")
                        .HasColumnType("longtext")
                        .HasColumnName("body2");

                    b.Property<string>("Body3")
                        .HasColumnType("longtext")
                        .HasColumnName("body3");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ListTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("list_title");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Tagline")
                        .HasColumnType("longtext")
                        .HasColumnName("tagline");

                    b.Property<string>("Title1")
                        .HasColumnType("longtext")
                        .HasColumnName("title1");

                    b.Property<string>("Title2")
                        .HasColumnType("longtext")
                        .HasColumnName("title2");

                    b.Property<string>("Title3")
                        .HasColumnType("longtext")
                        .HasColumnName("title3");

                    b.HasKey("Id")
                        .HasName("pk_home_content");

                    b.ToTable("home_content", (string)null);
                });

            modelBuilder.Entity("Domain.ImageGallery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<string>("ImageAlt")
                        .HasColumnType("longtext")
                        .HasColumnName("image_alt");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.HasKey("Id")
                        .HasName("pk_image_gallery");

                    b.ToTable("image_gallery", (string)null);
                });

            modelBuilder.Entity("Domain.Images", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<string>("Image1Path")
                        .HasColumnType("longtext")
                        .HasColumnName("image1path");

                    b.Property<string>("Image2Path")
                        .HasColumnType("longtext")
                        .HasColumnName("image2path");

                    b.Property<string>("Image3Path")
                        .HasColumnType("longtext")
                        .HasColumnName("image3path");

                    b.Property<string>("Image4Path")
                        .HasColumnType("longtext")
                        .HasColumnName("image4path");

                    b.Property<string>("Image5Path")
                        .HasColumnType("longtext")
                        .HasColumnName("image5path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_images");

                    b.ToTable("images", (string)null);
                });

            modelBuilder.Entity("Domain.ManagePreference", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("Email_Alert")
                        .HasColumnType("bigint")
                        .HasColumnName("email_alert");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<long>("Notification_Alert")
                        .HasColumnType("bigint")
                        .HasColumnName("notification_alert");

                    b.Property<long>("Sms_Alert")
                        .HasColumnType("bigint")
                        .HasColumnName("sms_alert");

                    b.Property<long>("User_Id")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_accountmanage_alert");

                    b.ToTable("accountmanage_alert", (string)null);
                });

            modelBuilder.Entity("Domain.MaritalStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_marital_status");

                    b.ToTable("marital_status", (string)null);
                });

            modelBuilder.Entity("Domain.MatchingProfiles", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<long>("PartnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("partner_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_matching_profiles");

                    b.ToTable("matching_profiles", (string)null);
                });

            modelBuilder.Entity("Domain.MotherTongue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_mother_tongue");

                    b.ToTable("mother_tongue", (string)null);
                });

            modelBuilder.Entity("Domain.Nationality", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .HasColumnType("longtext")
                        .HasColumnName("country_code");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<string>("FlagImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("flag_image_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_nationality");

                    b.ToTable("nationality", (string)null);
                });

            modelBuilder.Entity("Domain.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Is_Read")
                        .HasColumnType("int")
                        .HasColumnName("is_read");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<long>("Notify_Id")
                        .HasColumnType("bigint")
                        .HasColumnName("notify_id");

                    b.Property<string>("Notify_Message")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("notify_message");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notification");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("Domain.PageSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("BannerImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("banner_image_path");

                    b.Property<string>("BannerSubtitle")
                        .HasColumnType("longtext")
                        .HasColumnName("banner_subtitle");

                    b.Property<string>("BannerTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("banner_title");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("ParentName")
                        .HasColumnType("longtext")
                        .HasColumnName("parent_name");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("longtext")
                        .HasColumnName("seo_description");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("seo_title");

                    b.Property<bool>("ShowOnFooter")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("show_on_footer");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_page_settings");

                    b.ToTable("page_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "index",
                            ShowOnFooter = false,
                            Title = "Home"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 2L,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "result",
                            ParentName = "index",
                            ShowOnFooter = false,
                            Title = "Result"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 3L,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "error",
                            ParentName = "index",
                            ShowOnFooter = false,
                            Title = "Error"
                        });
                });

            modelBuilder.Entity("Domain.Profession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_profession");

                    b.ToTable("profession", (string)null);
                });

            modelBuilder.Entity("Domain.ProfileFor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_profile_for");

                    b.ToTable("profile_for", (string)null);
                });

            modelBuilder.Entity("Domain.Registration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("About")
                        .HasColumnType("longtext")
                        .HasColumnName("about");

                    b.Property<long>("BodyTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("body_type_id");

                    b.Property<long>("CasteId")
                        .HasColumnType("bigint")
                        .HasColumnName("caste_id");

                    b.Property<long>("CommunityId")
                        .HasColumnType("bigint")
                        .HasColumnName("community_id");

                    b.Property<string>("CompletedStep")
                        .HasColumnType("longtext")
                        .HasColumnName("completed_step");

                    b.Property<long>("ComplexionId")
                        .HasColumnType("bigint")
                        .HasColumnName("complexion_id");

                    b.Property<string>("Country")
                        .HasColumnType("longtext")
                        .HasColumnName("country");

                    b.Property<string>("CountryCode")
                        .HasColumnType("longtext")
                        .HasColumnName("country_code");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<string>("DOB")
                        .HasColumnType("longtext")
                        .HasColumnName("dob");

                    b.Property<string>("District")
                        .HasColumnType("longtext")
                        .HasColumnName("district");

                    b.Property<string>("EducationType")
                        .HasColumnType("longtext")
                        .HasColumnName("education_type");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("FamilyName")
                        .HasColumnType("longtext")
                        .HasColumnName("family_name");

                    b.Property<string>("FatherName")
                        .HasColumnType("longtext")
                        .HasColumnName("father_name");

                    b.Property<long>("FinancialStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("financial_status_id");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext")
                        .HasColumnName("gender");

                    b.Property<long>("HeightId")
                        .HasColumnType("bigint")
                        .HasColumnName("height_id");

                    b.Property<string>("HighestEducation")
                        .HasColumnType("longtext")
                        .HasColumnName("highest_education");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_complete");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPhysicallyChallenged")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_physically_challenged");

                    b.Property<bool>("IsPremiumMember")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_premium_member");

                    b.Property<bool>("IsSpecialRequest")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_special_request");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_verified");

                    b.Property<string>("LandlineNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("landline_number");

                    b.Property<long>("MaritalStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("marital_status_id");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<long>("MotherTongueId")
                        .HasColumnType("bigint")
                        .HasColumnName("mother_tongue_id");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<long>("NationalityId")
                        .HasColumnType("bigint")
                        .HasColumnName("nationality_id");

                    b.Property<long?>("NumberOfChildrens")
                        .HasColumnType("bigint")
                        .HasColumnName("number_of_childrens");

                    b.Property<string>("Password")
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.Property<string>("PinCode")
                        .HasColumnType("longtext")
                        .HasColumnName("pin_code");

                    b.Property<string>("Post")
                        .HasColumnType("longtext")
                        .HasColumnName("post");

                    b.Property<string>("PresentCountry")
                        .HasColumnType("longtext")
                        .HasColumnName("present_country");

                    b.Property<string>("PresentDistrict")
                        .HasColumnType("longtext")
                        .HasColumnName("present_district");

                    b.Property<string>("PresentState")
                        .HasColumnType("longtext")
                        .HasColumnName("present_state");

                    b.Property<long>("ProfessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("profession_id");

                    b.Property<string>("ProfessionType")
                        .HasColumnType("longtext")
                        .HasColumnName("profession_type");

                    b.Property<long>("ProfileForId")
                        .HasColumnType("bigint")
                        .HasColumnName("profile_for_id");

                    b.Property<string>("RegisterNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("register_number");

                    b.Property<long>("ReligionId")
                        .HasColumnType("bigint")
                        .HasColumnName("religion_id");

                    b.Property<long>("ReligiousnessId")
                        .HasColumnType("bigint")
                        .HasColumnName("religiousness_id");

                    b.Property<bool>("ShowOnHomePage")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("show_on_home_page");

                    b.Property<string>("State")
                        .HasColumnType("longtext")
                        .HasColumnName("state");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("longtext")
                        .HasColumnName("verification_code");

                    b.Property<string>("Village")
                        .HasColumnType("longtext")
                        .HasColumnName("village");

                    b.Property<long>("WeightId")
                        .HasColumnType("bigint")
                        .HasColumnName("weight_id");

                    b.HasKey("Id")
                        .HasName("pk_registration");

                    b.ToTable("registration", (string)null);
                });

            modelBuilder.Entity("Domain.ReligionCaste", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_religion_caste");

                    b.ToTable("religion_caste", (string)null);
                });

            modelBuilder.Entity("Domain.Religiousness", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<long?>("Type")
                        .HasColumnType("bigint")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_religiousness");

                    b.ToTable("religiousness", (string)null);
                });

            modelBuilder.Entity("Domain.SocialMedia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .HasColumnType("longtext")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_social_media");

                    b.ToTable("social_media", (string)null);
                });

            modelBuilder.Entity("Domain.UserFavouriteProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<long>("LikedId")
                        .HasColumnType("bigint")
                        .HasColumnName("liked_id");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_userfavoriteprofile");

                    b.ToTable("userfavoriteprofile", (string)null);
                });

            modelBuilder.Entity("Domain.UserStarProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<long>("StarId")
                        .HasColumnType("bigint")
                        .HasColumnName("star_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_userstaredprofile");

                    b.ToTable("userstaredprofile", (string)null);
                });

            modelBuilder.Entity("Application.Models.Transactions.Transaction", b =>
                {
                    b.HasOne("Domain.Registration", "Registration")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transaction_registration_registration_id");

                    b.Navigation("Registration");
                });
#pragma warning restore 612, 618
        }
    }
}
